// flow-typed signature: 1442eac3beaada98329a5bf354235509
// flow-typed version: <<STUB>>/@textpress/babel-preset-textpress_v*/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@textpress/babel-preset-textpress'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@textpress/babel-preset-textpress' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@textpress/babel-preset-textpress/index' {
  declare module.exports: $Exports<'@textpress/babel-preset-textpress'>;
}
declare module '@textpress/babel-preset-textpress/index.js' {
  declare module.exports: $Exports<'@textpress/babel-preset-textpress'>;
}
