// flow-typed signature: 057dcb8c603079d1851688ef4755ab47
// flow-typed version: <<STUB>>/mock-res_v^0.5.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mock-res'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mock-res' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mock-res/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mock-res/index' {
  declare module.exports: $Exports<'mock-res'>;
}
declare module 'mock-res/index.js' {
  declare module.exports: $Exports<'mock-res'>;
}
declare module 'mock-res/test.js' {
  declare module.exports: $Exports<'mock-res/test'>;
}
